### PR TITLE
EE8 OSGI changes Backport

### PR DESCRIPTION
**Pull request by tomjenkinson**
Jakarta EE 8

Based on https://github.com/eclipse-ee4j/jta-api/pull/187 and using some commits commits (plus changes to resolve merge conflicts) from https://github.com/eclipse-ee4j/jta-api/pull/188

I removed previous the signoff from the commits that I resolved the merge conflicts on and provided with my own

### CODE REVIEW

**Comment by grgrzybek** [comment]
```
+ cd api
+ mvn -B org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version
+ grep -E ^[0-9]+(\.[0-9]+)+-SNAPSHOT$
+ SNAPSHOT_VERSION=1.3.4-SNAPSHOT
+ cd ..
+ [ 1.3.4-SNAPSHOT = 1.* ]
+ [ 1.3.4-SNAPSHOT = 2.* ]
+ echo Unknown major version
Unknown major version
+ exit -1
```

I'm not sure what this may be...

**Comment by grgrzybek** [comment]
Build failed with
```
+ wget -q https://download.eclipse.org/ee4j/jakartaee-tck/8.0.1/promoted/jtatck-1.3_latest.zip -O jtatck.zip
Build step 'Execute shell' marked build as failure
```

**Comment by grgrzybek** [comment]
@tomjenkinson after some delay, I've sent a message [to jta-dev mailing list](https://www.eclipse.org/lists/jta-dev/msg00190.html) about possible jakarta.transactiona-api 1.3.4 release as promised.
Also, I've checked the commits to be merged to `RELEASE-1.3.3` branch and they look fine.

regards
Grzegorz Grzybek

**Review by LanceAndersen — APPROVED** [review]

**Review by mmusgrov — APPROVED** [review]
Looks fine (and identical to PR #188 apart from the target branch so I assume that was the intention).

**Pull request closed without merging**
